
name: Build ZMK firmware

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build ZMK using Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace             ghcr.io/zmkfirmware/zmk-dev-container:stable             /bin/bash -c "
              cd /workspace &&               west init -l config &&               west update &&               west build -s zmk/app -d build/chocofi_left -b nice_nano_v2 -- -DSHIELD=chocofi_left &&               west build -s zmk/app -d build/chocofi_right -b nice_nano_v2 -- -DSHIELD=chocofi_right
            "

      - name: Upload release
        uses: softprops/action-gh-release@v1
        if: success()
        with:
          name: "Chocofi Firmware - ${{ github.sha }}"
          tag_name: "chocofi-${{ github.sha }}"
          files: |
            build/chocofi_left/zephyr/zmk.uf2
            build/chocofi_right/zephyr/zmk.uf2
